filemanager/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("text_corrector.urls", namespace="text_corrector")),
    path("google-speech/", include("google_cloud_speech.urls", namespace="google_cloud_speech")),

]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

google_cloud_speech/urls.py
from django.urls import path
from . import views

app_name = "google_cloud_speech"

urlpatterns = [
    path("podaj-tekst", views.podaj_tekst, name="podaj_tekst"),
    path("text-to-audio/<str:file_name>", views.text_to_audio, name="text_to_audio"),
    path("text-to-speech/", views.text_to_speech, name="text_to_speech"),
    path("voice-files/", views.voice_files, name="voice_files"),
    path("load-voice-file/<str:path>/", views.load_voice_file, name="load_voice_file"),
    path("examine-voice-file/<str:text>", views.output_file, name="output_file"),
    path("speech-to-text/<str:local_file_path>/", views.speech_to_text, name="speech_to_text"),
]

google_cloud_speech/models.py
from django.db import models

# Create your models here.

google_cloud_speech/forms.py
from django import forms


class TextForm(forms.Form):
    text = forms.CharField(label="Tekst do zamiany na mowę", max_length=250)

google_cloud_speech/views.py
import glob
import io
import mimetypes
import os

from django.conf import settings
from django.http import HttpResponse
from django.shortcuts import render

from google.cloud import texttospeech
from google.cloud import speech_v1
from google.cloud.speech_v1 import enums
from slugify import slugify

from .forms import TextForm

"""Synthesizes speech from the input string of text or ssml.

Note: ssml must be well-formed according to:
    https://www.w3.org/TR/speech-synthesis/
"""


def text_to_speech(request):

    # Instantiates a client
    client = texttospeech.TextToSpeechClient()

    # Set the text input to be synthesized
    text = request.GET.get("results", "To wartość domyślna!")
    print(text)

    synthesis_input = texttospeech.SynthesisInput(text=text)

    # Build the voice request, select the language code ("en-US") and the ssml
    # voice gender ("neutral")
    voice = texttospeech.VoiceSelectionParams(
        language_code="pl-PL", ssml_gender=texttospeech.SsmlVoiceGender.MALE
    )
    voices = client.list_voices(request={"language_code": "pl"})

    # Select the type of audio file you want returned
    audio_config = texttospeech.AudioConfig(
        audio_encoding=texttospeech.AudioEncoding.LINEAR16
    )

    # Perform the text-to-speech request on the text input with the selected
    # voice parameters and audio file type
    # response = client.synthesize_speech(synthesis_input, voice, audio_config)
    response = client.synthesize_speech(
        request={
            "input": synthesis_input,
            "voice": voice,
            "audio_config": audio_config
        }
    )

    # The response's audio_content is binary.
    slug_text = slugify(text)
    if len(slug_text) < 20:
        slug_text = slug_text + (20 - len(slug_text)) * "_"
    else:
        slug_text = slug_text[:20]
    file_path = settings.MEDIA_ROOT + "/" + slug_text + ".wav"

    with open(file_path, "wb") as out:
        # Write the response to the output file.
        out.write(response.audio_content)
        print(f'Audio content written to file {slug_text}.wav"')
    return render(
        request,
        "google_cloud_speech/text-to-speech.html",
        {"text": text, "slug_text": slug_text},
    )


def text_to_audio(request, file_name):

    client = texttospeech.TextToSpeechClient()

    # Set the text input from file to be synthesized
    file_path = settings.MEDIA_ROOT + "/" + file_name
    counter_of_lines = 0
    with open(file_path, "r+") as fp:
        directory_to_create = settings.MEDIA_ROOT + "/" + str(file_name)[:-4]
        create_directory(directory_to_create)
        for line in fp:
            counter_of_lines += 1
            print(line)
            synthesis_input = texttospeech.SynthesisInput(text=line)

            # Build the voice request, select the language code ("pl-PL") and the ssml
            # voice gender ("neutral" or "male" or "female")
            voice = texttospeech.VoiceSelectionParams(
                language_code="pl-PL", ssml_gender=texttospeech.SsmlVoiceGender.MALE
            )
            # voices = client.list_voices(request={"language_code": "pl"})

            # Select the type of audio file you want returned
            audio_config = texttospeech.AudioConfig(
                audio_encoding=texttospeech.AudioEncoding.LINEAR16
            )

            # Perform the text-to-speech request on the text input with the selected
            # voice parameters and audio file type
            response_from_tts = client.synthesize_speech(
                request={
                    "input": synthesis_input,
                    "voice": voice,
                    "audio_config": audio_config
                }
            )
            path_to_save_audio = directory_to_create + "/" + str(counter_of_lines) + ".wav"

            with open(path_to_save_audio, "wb") as out:
                # Write the response to the output file.
                out.write(response_from_tts.audio_content)
                print(f'Audio content written to file {counter_of_lines}.wav"')

    response = HttpResponse(f"Created {counter_of_lines} audio files.")
    return response


def create_directory(path):
    try:
        os.mkdir(path)
    except OSError:
        print("Creation of the directory %s failed" % path)
    else:
        print("Successfully created the directory %s " % path)


def podaj_tekst(request):
    return render(request, "google_cloud_speech/podaj_tekst.html")


def output_file(request, text):
    file_path = os.path.join(settings.MEDIA_ROOT) + "/" + text + ".wav"
    if os.path.exists(file_path):
        with open(file_path, "rb") as fh:
            mime_type, _ = mimetypes.guess_type(file_path)
            response = HttpResponse(fh.read(), content_type=mime_type)
            response["Content-Disposition"] = "inline; filename=" + os.path.basename(
                file_path
            )
            return response
        raise Http404("Nie ma takiego pliku!")
    else:
        return render(request, "text_corrector/404.html")


def voice_files(request):
    voice_files_list = []
    dir_path = settings.MEDIA_ROOT
    for full_path in glob.iglob(dir_path + '/' + '*.wav'):
        voice_files_list.append([os.path.basename(full_path), os.path.basename(full_path)[:-4]])
    return render(request, "google_cloud_speech/voice-files.html", {'voice_files_list': voice_files_list})


def load_voice_file(request, path):
    file_path = os.path.join(settings.MEDIA_ROOT, path)
    if os.path.exists(file_path):
        with open(file_path, "rb") as fh:
            mime_type, _ = mimetypes.guess_type(file_path)
            response = HttpResponse(fh.read(), content_type=mime_type)
            response["Content-Disposition"] = "inline; filename=" + os.path.basename(
                file_path
            )
            return response
        raise Http404("Nie ma takiego pliku!")
    else:
        return render(request, "text_corrector/404.html")


def speech_to_text(request, local_file_path):
    """
    Transcribe a short audio file using synchronous speech recognition

    Args:
      local_file_path Path to local audio file, e.g. /path/audio.wav
    """

    client = speech_v1.SpeechClient()

    # local_file_path = 'resources/brooklyn_bridge.raw'

    # The language of the supplied audio
    language_code = "pl-PL"

    # Sample rate in Hertz of the audio data sent
    sample_rate_hertz = 24000  # było 16000

    # Encoding of audio data sent. This sample sets this explicitly.
    # This field is optional for FLAC and WAV audio formats.
    encoding = enums.RecognitionConfig.AudioEncoding.LINEAR16
    config = {
        "language_code": language_code,
        # "sample_rate_hertz": sample_rate_hertz,
        "encoding": encoding,
    }
    local_full_path = settings.MEDIA_ROOT + '/' + local_file_path
    local_file_name = local_file_path[:-4]
    with io.open(local_full_path, "rb") as f:
        content = f.read()
    audio = {"content": content}

    response = client.recognize(config, audio)
    for result in response.results:
        # First alternative is the most probable result
        alternative = result.alternatives[0]
        print(u"Transcript: {}".format(alternative.transcript))
        print(u"Confidence: {}".format(alternative.confidence))

    return render(
        request,
        "google_cloud_speech/speech-to-text.html",
        {"text": alternative.transcript,
         'confidence': alternative.confidence,
         'local_file_name': local_file_name},
    )

google_cloud_speech/templates/google_cloud_speech/podaj_tekst.html
{% extends 'text_corrector/base.html' %}
{% load static %}

{% block content %}
    <div class="row">
      <div class="jumbotron align-items-center">
          <h1 class="display-6  text-justified">Wysyłka tekstu do usługi Text-To-Speech</h1>
          <p class="lead">Plik wynikowy zapisywany jest w folderze z danymi,
                  domyślna nazwa to 'output.wav'. Dostępne są również inne rodzaje kodowania, szczegóły w dokumentacji.</p>
      </div>

      <form method="get" action="{% url 'google_cloud_speech:text_to_speech' %}" class="col-lg-12">
        <div class="form-group form-group-lg row">
          <div class="col-lg-12 align-items-center">
              <textarea type="text" class="form-control form-control-lg" id="results" name="results" placeholder="Wpisz tekst do syntezy" rows="5" cols="80"></textarea>
            <button type="submit" class="btn btn-lg btn-primary" id="guzik-tts">Wyślij do usługi Text-To-Speech</button>
          </div>
        </div>
      </form>

    </div>
{% endblock content %}

google_cloud_speech/templates/google_cloud_speech/speech-to-text.html
{% extends 'text_corrector/base.html' %}
{% load static %}

{% block content %}
    <div class="row">

        <div class="jumbotron align-items-center">
          <h1 class="display-6  text-justified">Sprawdź tekst!</h1>
          <p class="lead">Uważnie przeczytaj rozpoznany tekst na tej stronie.
            Jeśli jesteś <b>pewien</b>, że tekst odbiega od tego co usłyszałeś
              - nie bądź bezczynny i zgłoś to do osoby zaangażowanej w projekt  &hearts;</p>
        </div>

        <div class="d-inline col-lg-8">
               <audio controls autoplay>
                    <source id="wav"
                            src="{% url 'google_cloud_speech:output_file' local_file_name %}"
                            type="audio/wav"
                            onloadeddata="">
                    Your browser does not support the audio element.
                </audio>
        </div>
        <div class="d-inline">
            <a href="{% url 'google_cloud_speech:voice_files' %}" class="btn btn-primary">Przejdź do listy nagrań</a>
        </div>
        <h3>[TEKST ROZPOZNANY]: <b class="text-monospace">{{ text }}</b></h3>
        <h4>[Pewność rozpoznania]: {{ confidence }}</h4>
    </div>

{% endblock content %}

google_cloud_speech/templates/google_cloud_speech/text-to-speech.html
{% extends 'text_corrector/base.html' %}
{% load static %}

{% block content %}
    <div class="row">

        <div class="jumbotron align-items-center">
          <h1 class="display-6  text-justified">Odsłuchaj plik!</h1>
          <p class="lead">Uważnie wysłuchaj pliku .wav na tej stronie.
            Jeśli jesteś <b>pewien</b>, że tekst odbiega od tego co usłyszałeś
              - nie bądź bezczynny i zgłoś to do osoby zaangażowanej w projekt  &hearts;</p>
        </div>

        <div class="align-items-center col-lg-10">
               <audio controls autoplay>
                    <source id="wav"
                            src="{% url 'google_cloud_speech:output_file' %}"
                            type="audio/wav"
                            onloadeddata="">
                    Your browser does not support the audio element.
                </audio>
                <a href="{% url 'google_cloud_speech:podaj_tekst' %}" class="btn btn-primary">Wpisz nowy tekst</a>
        </div>
    </div>

{% endblock content %}

google_cloud_speech/templates/google_cloud_speech/voice-files.html
{% extends 'text_corrector/base.html' %}
{% load static %}
{% get_media_prefix as MEDIA_PREFIX %}
{% load proper_paginate %}
{% load url_replace %}

{% block content %}
    <div class="row">

      <div class="jumbotron align-items-center">
          <h1 class="display-6  text-justified">Edycja tekstu dla plików .wav</h1>
          <p class="lead">Lista plików dźwiękowych, dostępnych w katalogu roboczym.
              Odsłuchaj plik, a po wciśnięciu strzałki po prawej, zostanie uruchomiona
              usługa Speech-To-Text.
              Dostępny będzie rozpoznany tekst oraz prawdopodobieństwo jego poprawności.
          </p>
      </div>

        {% for vf in voice_files_list %}
            <table class="table table-bordered border table-striped">
              <tbody>
                <tr class="bg-warning">
                    <td>Odtwórz plik <b>{{ vf.0 }}</b>:
                      <audio controls autoplay>
                        <source id="wav"
                                src="{% url 'google_cloud_speech:output_file' vf.1 %}"
                                type="audio/wav"
                                onloadeddata="">
                            Your browser does not support the audio element.
                      </audio></td>
                  <td><a href="{% url 'google_cloud_speech:speech_to_text' vf.0 %}"><i class="fas fa-share fa-2x float-right"></i></a></td>
                </tr>
              </tbody>
            </table>
            <hr>
        {% endfor %}


    </div>

{% endblock content %}