filemanager/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("text_corrector.urls", namespace="text_corrector")),
    path("google-speech/", include("google_cloud_speech.urls", namespace="google_cloud_speech")),

]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

google_cloud_speech/urls.py
from django.urls import path
from . import views

app_name = "google_cloud_speech"

urlpatterns = [
    path("podaj-tekst", views.podaj_tekst, name="podaj_tekst"),
    path("text-to-audio/<str:file_name>", views.text_to_audio, name="text_to_audio"),
    path("text-to-speech/", views.text_to_speech, name="text_to_speech"),
    path("voice-files/", views.voice_files, name="voice_files"),
    path("load-voice-file/<str:path>/", views.load_voice_file, name="load_voice_file"),
    path("examine-voice-file/<str:text>", views.output_file, name="output_file"),
    path("speech-to-text/<str:local_file_path>/", views.speech_to_text, name="speech_to_text"),
]

text_corrector/urls.py
from django.urls import path
from . import views

app_name = "text_corrector"

urlpatterns = [
    path("", views.index, name="index"),
    path("lista-wave-tekst", views.wave_list, name="wave_list"),
    path("wave-tekst/<int:pk>/edycja/", views.wave_text_edit, name="wave_text_edit"),
    path("wave-tekst/<int:pk>/", views.wave_text_detail, name="wave_text_detail"),
    path("download/<str:path>.wav/", views.download_file, name="download_file"),
]

text_corrector/models.py
from django.db import models


class WaveText(models.Model):
    name = models.CharField(max_length=100)
    before_normalization = models.TextField(max_length=300)
    after_normalization = models.CharField(max_length=300)
    modified = models.BooleanField(default=False)

    class Meta:
        verbose_name_plural = "Teksty w plikach wave"

    def __str__(self):
        return self.name


class CsvFile(models.Model):
    file_path = models.CharField(max_length=100)

    class Meta:
        verbose_name_plural = "Pliki CSV"

    def __str__(self):
        return self.file_path

text_corrector/forms.py
from django import forms

from .models import WaveText


class WaveTextForm(forms.ModelForm):
    class Meta:
        model = WaveText
        fields = ("before_normalization",)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['before_normalization'].widget.attrs.update(rows='4')

text_corrector/views.py
import mimetypes
import os

from django.conf import settings
from django.core.paginator import EmptyPage, Paginator, PageNotAnInteger
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse, Http404

from .models import WaveText
from .forms import WaveTextForm


def index(request):
    return render(request, "text_corrector/index.html")


def wave_list(request):
    wave_texts = WaveText.objects.all().order_by("name")[:50]
    paginator = Paginator(wave_texts, 3)
    page = request.GET.get("page")
    try:
        texts = paginator.page(page)
    except PageNotAnInteger:
        texts = paginator.page(1)
    except EmptyPage:
        texts = paginator.page(paginator.num_pages)
    return render(
        request,
        "text_corrector/wave_list.html",
        {"page": page, "texts": texts, "wave_texts": wave_texts},
    )


def wave_text_detail(request, pk):
    wave_text = get_object_or_404(WaveText, pk=pk)
    return render(
        request, "text_corrector/wave_text_detail.html", {"wave_text": wave_text}
    )


def wave_text_edit(request, pk):
    wave_text = get_object_or_404(WaveText, pk=pk)
    if request.method == "POST":
        form = WaveTextForm(request.POST, instance=wave_text)
        if form.is_valid():
            wave_text.modified = True
            wave_text = form.save(commit=False)
            wave_text.save()
            return redirect("text_corrector:wave_text_detail", pk=wave_text.pk)
    else:
        form = WaveTextForm(instance=wave_text)
    return render(
        request,
        "text_corrector/wave_text_edit.html",
        {"form": form, "wave_text": wave_text},
    )


def download_file(request, path):
    file_path = os.path.join(settings.MEDIA_ROOT, path) + ".wav"
    if os.path.exists(file_path):
        with open(file_path, "rb") as fh:
            mime_type, _ = mimetypes.guess_type(file_path)
            response = HttpResponse(fh.read(), content_type=mime_type)
            response["Content-Disposition"] = "inline; filename=" + os.path.basename(
                file_path
            )
            return response
        raise Http404("Nie ma takiego pliku!")
    else:
        return render(request, "text_corrector/404.html")

text_corrector/templates/text_corrector/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

    <head>

      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
      <meta name="description" content="">
      <meta name="author" content="">

      <title>Toucan Giant-AI</title>
     <link rel="shortcut icon" type="image/png" href="{% static 'favicon.ico' %}"/>

      <!-- Bootstrap core CSS -->
      <link href="{% static 'bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
      <link href="{% static 'fontawesome-free-5.12.1-web/css/all.css' %}" rel="stylesheet">
      <link href="{% static 'css/custom.css' %}" rel="stylesheet">

    </head>

    <body>

      <!-- Navigation -->
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark static-top">
        <div class="container">
          <a class="navbar-brand" href="{% url 'text_corrector:index' %}">Toucan Giant-AI</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto">
              <li class="nav-item active">
                <a class="nav-link" href="{% url 'text_corrector:wave_list' %}">Wave text editor</a>
              </li>
              <li class="nav-item active">
                <a class="nav-link" href="{% url 'google_cloud_speech:podaj_tekst' %}">Text-To-Speech</a>
              </li>
              <li class="nav-item active">
                <a class="nav-link" href="{% url 'google_cloud_speech:voice_files' %}">Speech-To-Text</a>
              </li>
                <li class="nav-item active">
                <a class="nav-link" href="{% url 'google_cloud_speech:voice_files' %}">GCP-TF2 (not working yet)</a>
              </li>
              <li class="nav-item">
                {% if request.user.is_authenticated %}
                <a class="nav-link" href="{% url 'admin:logout' %}">Wyloguj z panelu</a>
                {% else %}
                <a class="nav-link" href="{% url 'admin:login' %}">Zaloguj do panelu</a>

                {% endif %}
              </li>
            </ul>
          </div>
        </div>
      </nav>

      <!-- Page Content -->
      <div class="container main-content">
          {% block content %}

          {% endblock content %}
      </div>

       <!-- Footer -->
      <footer class="py-5 bg-dark">
        <div class="container">
          <p class="m-0 text-center text-white">Toucan Systems &copy; Giant-AI, 2020</p>
        </div>
        <!-- /.container -->
      </footer>

      <!-- Bootstrap core JavaScript -->
      <script src="{% static 'jquery/jquery.slim.min.js' %}"></script>
      <script src="{% static 'bootstrap/js/bootstrap.bundle.min.js' %}"></script>
      <script src="{% static 'jquery/sticky-footer.min.js' %}"></script>
      <script>
        var stickyFooter = new StickyFooter('.main-content');
      </script>
    {% block additional_js %}
    {% endblock additional_js %}
    </body>

</html>

text_corrector/templates/text_corrector/index.html
{% extends 'text_corrector/base.html' %}
{% load static %}

{% block content %}
    <div class="row">
      <div id="carouselExampleSlidesOnly" class="carousel slide" data-ride="carousel">
          <div class="carousel-inner">
            <div class="carousel-item active">
              <img class="d-block w-100" src="{% static 'images/toucan-index.png' %}" alt="Starting slide">
            </div>
          </div>
        </div>
    </div>
{% endblock content %}

text_corrector/templates/text_corrector/wave_list.html
{% extends 'text_corrector/base.html' %}
{% load proper_paginate %}
{% load url_replace %}

{% block content %}
    <div class="row">

      <div class="jumbotron align-items-center">
          <h1 class="display-6  text-justified">Edycja tekstu dla plików .wav</h1>
          <p class="lead">Pierwsza linia zawiera nazwę pliku,
                  druga - tekst przed normalizacją,
                  trzecia - tekst po normalizacji.
              Edytowany jest <b>tylko</b> tekst przed normalizacją.</p>
      </div>

        {% for wt in texts %}
            <table class="table table-bordered border table-striped">
              <tbody>
                <tr class="bg-success">
                  <td>Pobierz plik: <a href="{% url 'text_corrector:download_file' wt.name %}" >{{ wt.name }}</a></td>
                  <td>Czy poprawiony? - {{ wt.modified }}</td>
                </tr>
                <tr>
                  <td colspan="2">{{ wt.before_normalization }}
                      <a href="{% url 'text_corrector:wave_text_edit' pk=wt.pk %}"><i class="fas fa-edit fa-2x float-right"></i></a>
                  </td>

                </tr>
                <tr>
                  <td colspan="2">{{ wt.after_normalization }}</td>
                </tr>
              </tbody>
            </table>
            <hr>
        {% endfor %}

        {% if texts.has_other_pages %}
            <ul class="pagination pagination-lg justify-content-center">
                {% if texts.number == 1 %}
                    <li class="disabled"><a class="page-link">⇤</a></li>
                {% else %}
                    <li><a class="page-link" href="?{% url_replace request 'page' 1 %}">⇤</a></li>
                {% endif %}
                {% if texts.has_previous %}
                    <li><a class="page-link" href="?{% url_replace request 'page' texts.previous_page_number %}">&laquo;</a></li>
                {% else %}
                    <li class="disabled"><a class="page-link">&laquo;</a></li>
                {% endif %}
                {% for i in texts.paginator|proper_paginate:texts.number %}
                    {% if texts.number == i %}
                        <!--<li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>-->
                        <li class="page-item active" aria-current="page"><a class="page-link">{{ i }}</a></li>
                    {% else %}
                        <li><a class="page-link" href="?{% url_replace request 'page' i %}">{{ i }}</a></li>
                    {% endif %}
                {% endfor %}
                {% if texts.has_next %}
                    <li><a class="page-link" href="?{% url_replace request 'page' texts.next_page_number %}">&raquo;</a></li>
                {% else %}
                    <li class="disabled"><a class="page-link">&raquo;</a></li>
                {% endif %}
                {% if texts.number == texts.paginator.num_pages %}
                    <li class="disabled"><a class="page-link">⇥</a></li>
                {% else %}
                    <li><a class="page-link" href="?{% url_replace request 'page' texts.paginator.num_pages %}">⇥</a></li>
                {% endif %}
            </ul>
        {% endif %}
    </div>

{% endblock content %}

text_corrector/templates/text_corrector/wave_text_detail.html
{% extends 'text_corrector/base.html' %}
{% load static %}

{% block content %}
    <div class="row">
        <table class="table table-bordered border table-striped">
          <tbody>
            <tr class="bg-success">
                <td><h3><a href="{% url 'text_corrector:download_file' wave_text.name %}" >{{ wave_text.name }}</a></h3></td>
                <td><h3>Czy poprawiony? - {{ wave_text.modified }}</h3></td>
            </tr>
            <tr>
                <td colspan="2"><h3>{{ wave_text.before_normalization }}</h3>
                  <a href="{% url 'text_corrector:wave_text_edit' pk=wave_text.pk %}"><i class="fas fa-edit fa-2x float-right"></i></a>
              </td>

            </tr>
            <tr>
                <td colspan="2"><h3>{{ wave_text.after_normalization }}</h3></td>
            </tr>
          </tbody>
        </table>
        <a href="{% url 'text_corrector:wave_list' %}" class="btn btn-primary">Wróć do listy plików</a>
    </div>

{% endblock content %}

text_corrector/templates/text_corrector/wave_text_edit.html
{% extends 'text_corrector/base.html' %}
{% load static %}
{% load widget_tweaks %}

<!DOCTYPE html>
<html lang="en">

    <head>

      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
      <meta name="description" content="">
      <meta name="author" content="">

      <title>Toucan Giant-AI</title>
     <link rel="shortcut icon" type="image/png" href="{% static 'favicon.ico' %}"/>

      <!-- Bootstrap core CSS -->
      <link href="{% static 'bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
      <link href="{% static 'fontawesome-free-5.12.1-web/css/all.css' %}" rel="stylesheet">
      <link href="{% static 'css/custom.css' %}" rel="stylesheet">

    </head>

    <body>

      <!-- Navigation -->
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark static-top">
        <div class="container">
          <a class="navbar-brand" href="{% url 'text_corrector:index' %}">Toucan Giant-AI</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto">
              <li class="nav-item active">
                <a class="nav-link" href="{% url 'text_corrector:wave_list' %}">Wave text editor</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'admin:login' %}">Zaloguj</a>
              </li>
            </ul>
          </div>
        </div>
      </nav>

      <!-- Page Content -->
      {% block content %}
        <div class="jumbotron align-items-center">
          <h1 class="display-6  text-justified">Edycja pliku - bądź ostrożny!</h1>
          <p class="lead">Uważnie wysłuchaj pliku .wav na tej stronie lub pobranego wcześniej.
            Jeśli jesteś <b>pewien</b>, że tekst odbiega od tego co usłyszałeś - zmień tekst. Po zakończeniu pracy z plikiem zapisz zmiany!</p>
        </div>
        <audio controls autoplay>
            <source id="wav"
                    src="{% url 'text_corrector:download_file' wave_text.name %}"
                    type="audio/wav"
                    onloadeddata="">
            Your browser does not support the audio element.
        </audio>

        <form method="post" class="align-items-center" novalidate>
          {% csrf_token %}

          {% for hidden_field in form.hidden_fields %}
            {{ hidden_field }}
          {% endfor %}

          {% for field in form.visible_fields %}
            <div class="form-group align-items-center float-center">
              <!--{{ field.label_tag }}-->
              {% render_field field class="form-control" %}
              {% if field.help_text %}
                <small class="form-text text-muted">{{ field.help_text }}</small>
              {% endif %}
            </div>
          {% endfor %}

          <button type="submit" class="btn btn-danger">Potwierdź poprawność tekstu</button>
          <a href="{% url 'text_corrector:wave_list' %}" class="btn btn-primary">Wróć do listy plików</a>

        </form>
        {% endblock content %}

       <!-- Footer -->
      <footer class="py-5 bg-dark">
        <div class="container">
          <p class="m-0 text-center text-white">Toucan Systems &copy; Giant-AI, 2020</p>
        </div>
        <!-- /.container -->
      </footer>

      <!-- Bootstrap core JavaScript -->
      <script src="{% static 'jquery/jquery.slim.min.js' %}"></script>
      <script src="{% static 'jquery/sticky-footer.min.js' %}"></script>
      <script src="{% static 'bootstrap/js/bootstrap.bundle.min.js' %}"></script>
      <script>
        var stickyFooter = new StickyFooter('.main-content');
      </script>
      {% block additional_js %}
        <script>
          $("#wav").on("error", function (e) {
            alert("Brak pliku .wav!");
          });
        </script>
      {% endblock additional_js %}

    </body>

</html>